### ISSUE TITLE
prefix _

### ISSUE THREAD

**Issue by matthieugomez** [mdroste/stata-fastreshape#1]
Great package!

However, it seems like the command returns the wrong output when variables start with the prefix  _.
```
clear all
set obs 10
gen id = _n
gen _1 = 1
gen _2 = 2
fastreshape long _, i(id) j(new)
```
returns 
```
#> id new _1   _2
#> 1  1        1     .
#> 1  2        .     2
```

**Comment by mdroste** [comment]
Hi Matthieu,

Great catch! This issue has been fixed in the most recent version with a more robust method of handling renames. Please let me know if you encounter any more bugs along these lines.

Best,
Mike
